In [2]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df = pd.read_csv("./bases/suicide/master_correcao.csv") 
dfsuicides = df.pivot_table('suicides', ['country'], 'year')
#dfsuicides
dfsuicides = dfsuicides.interpolate(method='linear',limit_direction='both', axis=1)
dfsuicides = pd.melt(dfsuicides.reset_index(), id_vars=["country"], 
                  var_name="year", value_name="suicides")

In [4]:
dfpopulation = df.pivot_table('population', ['country'], 'year')
dfpopulation = dfpopulation.interpolate(method='linear', limit_direction ='backward', axis=1)
dfpopulation = pd.melt(dfpopulation.reset_index(), id_vars=["country"], 
                  var_name="year", value_name="population")

In [5]:
dffinal = dfpopulation.merge(dfsuicides).sort_values(['country','year']).reset_index(drop=True)
dffinal['suicides100'] = (dffinal['suicides'] * 100000 ) / dffinal['population']
dffinal

                  country  year   population  suicides  suicides100
0                 Albania  2000    3089027.0      54.0     1.748123
1                 Albania  2001    3060173.0     119.0     3.888669
2                 Albania  2002    3051010.0     133.0     4.359212
3                 Albania  2003    3039616.0     124.0     4.079463
4                 Albania  2004    3026939.0     146.0     4.823355
5                 Albania  2005    3011487.0       0.0     0.000000
6                 Albania  2006    2992547.0       0.0     0.000000
7                 Albania  2007    2970017.0     124.0     4.175060
8                 Albania  2008    2947314.0     160.0     5.428672
9                 Albania  2009    2927519.0       0.0     0.000000
10                Albania  2010    2913021.0      96.0     3.295548
11                Albania  2011    2905195.0      96.0     3.304425
12                Albania  2012    2900401.0      96.0     3.309887
13                Albania  2013    2895092.0      96.0     3.315957
14                Albania  2014    2889104.0      96.0     3.322830
15                Albania  2015    2880703.0      96.0     3.332520
16    Antigua and Barbuda  2000      83584.0       2.0     2.392802
17    Antigua and Barbuda  2001      85057.0       2.0     2.351364
18    Antigua and Barbuda  2002      86266.0       0.0     0.000000
19    Antigua and Barbuda  2003      87293.0       1.0     1.145567
20    Antigua and Barbuda  2004      88257.0       2.0     2.266109
21    Antigua and Barbuda  2005      89253.0       0.0     0.000000
22    Antigua and Barbuda  2006      90301.0       0.0     0.000000
23    Antigua and Barbuda  2007      91381.0       1.0     1.094319
24    Antigua and Barbuda  2008      92478.0       0.0     0.000000
25    Antigua and Barbuda  2009      93581.0       0.0     0.000000
26    Antigua and Barbuda  2010      94661.0       0.0     0.000000
27    Antigua and Barbuda  2011      95719.0       0.0     0.000000
28    Antigua and Barbuda  2012      96777.0       0.0     0.000000
29    Antigua and Barbuda  2013      97824.0       0.0     0.000000
...                   ...   ...          ...       ...          ...
1282        United States  2002  287625193.0   31645.0    11.002166
1283        United States  2003  290107933.0   31477.0    10.850100
1284        United States  2004  292805298.0   32428.0    11.074936
1285        United States  2005  295516599.0   32629.0    11.041343
1286        United States  2006  298379912.0   33292.0    11.157588
1287        United States  2007  301231207.0   34596.0    11.484866
1288        United States  2008  304093966.0   36030.0    11.848311
1289        United States  2009  306771529.0   36900.0    12.028496
1290        United States  2010  309348193.0   38362.0    12.400913
1291        United States  2011  311663358.0   39508.0    12.676498
1292        United States  2012  313998379.0   40596.0    12.928729
1293        United States  2013  316204908.0   41143.0    13.011499
1294        United States  2014  318563456.0   42769.0    13.425583
1295        United States  2015  320896618.0   44189.0    13.770479
1296              Uruguay  2000    3321245.0     555.0    16.710601
1297              Uruguay  2001    3327103.0     499.0    14.998033
1298              Uruguay  2002    3327773.0     675.0    20.283835
1299              Uruguay  2003    3325637.0     535.0    16.087144
1300              Uruguay  2004    3324096.0     520.0    15.643351
1301              Uruguay  2005    3325612.0     498.0    14.974687
1302              Uruguay  2006    3331043.0     528.0    15.850891
1303              Uruguay  2007    3339741.0     576.0    17.246846
1304              Uruguay  2008    3350824.0     523.0    15.608101
1305              Uruguay  2009    3362755.0     511.0    15.195874
1306              Uruguay  2010    3374415.0     547.0    16.210217
1307              Uruguay  2011    3385624.0     573.0    16.924502
1308              Uruguay  2012    3396777.0     599.0    17.634363
1309              Uruguay  2013    3408005.0     546.0    16.021103
1310              Uruguay  2014    3419546.0     591.0    17.282996
1311              Uruguay  2015    3431552.0     630.0    18.359040

[1312 rows x 5 columns]

In [ ]:
unico = dffinal['country'].unique()

In [ ]:
fig, ax = plt.subplots()
dffinal.where(dffinal.country=='Brazil').plot(x='year', y='suicides100', ax=ax)
#plt.plot(data=dfsuicide100, marker='o', markerfacecolor='olive', color='y', linewidth=2, markersize=4)

In [ ]:
df2 = pd.read_csv("./bases/wdi/Indicators.csv")

In [ ]:
filtro = df2.IndicatorCode.isin(['SP.DYN.LE00.IN','SP.DYN.LE00.FE.IN','SP.DYN.LE00.MA.IN', 'BX.TRF.PWKR.CD.DT','SP.POP.GROW','SP.DYN.CBRT.IN','NY.GNP.MKTP.CD', 'IC.TAX.PAYM','FP.CPI.TOTL','SL.EMP.MPYR.ZS','GC.XPN.TOTL.CN','SL.TLF.PRIM.ZS'])
filtro3 = df2.Year > 1999 
filtro4 = df2.Year < 2016
df2 = df2[filtro & filtro3 & filtro4]

In [ ]:
df2.replace(["Slovak Republic", "Kyrgyz Republic","St. Lucia","Bahamas, The","Korea, Dem. Rep.","St. Vincent and the Grenadines","Russia"], ['Slovakia', 'Kyrgyzstan', 'Saint Lucia', 'Bahamas', 'Republic of Korea', 'Saint Vincent and Grenadines','Russian Federation'], inplace=True)                                 
filtro2 = df2.CountryName.isin(['Albania', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Australia', 'Austria', 'Bahamas', 'Bahrain', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Brazil', 'Bulgaria', 'Canada', 'Chile', 'Colombia', 'Costa Rica', 'Croatia', 'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Ecuador', 'El Salvador', 'Estonia', 'Fiji', 'Finland', 'France', 'Georgia', 'Germany', 'Greece', 'Grenada', 'Guatemala', 'Guyana', 'Hungary', 'Iceland', 'Ireland', 'Israel', 'Italy', 'Japan', 'Kazakhstan', 'Kuwait', 'Kyrgyzstan', 'Latvia', 'Lithuania', 'Luxembourg', 'Malta', 'Mauritius', 'Mexico', 'Netherlands', 'New Zealand', 'Norway', 'Panama', 'Paraguay', 'Poland', 'Portugal', 'Puerto Rico', 'Qatar', 'Republic of Korea', 'Romania', 'Russian Federation', 'Saint Lucia', 'Saint Vincent and Grenadines', 'Serbia', 'Seychelles', 'Singapore', 'Slovakia', 'Slovenia', 'South Africa', 'Spain', 'Suriname', 'Sweden', 'Switzerland', 'Thailand', 'Trinidad and Tobago', 'Turkmenistan', 'Ukraine', 'United Kingdom', 'United States', 'Uruguay'])
df2 = df2[filtro2].reset_index(drop=True)
df2.rename(columns={'CountryName':'country','CountryCode':'coyntrycode'}, inplace=True)

In [ ]:
dfpais = df2[['country','coyntrycode']].drop_duplicates().reset_index(drop=True)
df_inner = pd.merge(dfpais, dffinal, on='country', how='inner')

In [ ]:
df3 = pd.read_excel("./bases/economic/Unemployment.xlsx")
df3.rename(columns={'Unnamed: 0':'Year'}, inplace=True)
df3 = pd.melt(df3.reset_index(), id_vars=["Year"],var_name="Country", value_name="unemployment")
filtro5 = df3.Year > 1999 
filtro6 = df3.Year < 2016
df3 = df3[filtro5 & filtro6]

In [ ]:
df4 = pd.read_csv("./bases/education/EdStatsData.csv")

In [ ]:
from pandas.api.types import is_number
df4 = pd.melt(df4, id_vars=["Country Code","Indicator Code"],var_name="Year", value_name="value")
df4 = df4[df4.Year.apply(lambda x: x.isnumeric())]
filtro7 = df4.Year > 1999 
filtro8 = df4.Year < 2016
df4 = df4[filtro7 & filtro8]

In [ ]:
df4